### ISSUE TITLE
fabs() is rertuning wrong values for 128-bit type

### ISSUE THREAD

**Issue by tuliom** [libdfp/libdfp#13]
It's happening on ppc64 and ppc64le, with different distributions.

Output of test-fabs-d128:
Failure: Test: fabs (-42)
Result:
 is:         -4.20000000000000000000e+01  -4.2000000000000000000000000000000000e+01
 should be:   4.20000000000000000000e+01  4.2000000000000000000000000000000000e+01
 difference: -8.40000000000000000000e+01  -8.4000000000000000000000000000000000e+01
 ulp       : -8400000000000000000000000000000000.0000
 max.ulp   :  0.0000
Failure: Test: fabs (-2.718281828459045235360287471352662)
Result:
 is:         -2.71828182845904523536e+00  -2.7182818284590452353602874713526620e+00
 should be:   2.71828182845904523536e+00  2.7182818284590452353602874713526620e+00
 difference: -5.43656365691809047072e+00  -5.4365636569180904707205749427053240e+00
 ulp       : -5436563656918090470720574942705324.0000
 max.ulp   :  0.0000

**Comment by zatrazz** [comment]
The problem for powerpc optimized routine is it assumes that __Decimal128 will be passed using 'fp0', while it is passed and returned in fp2 and fp3 (it requires by ABI to use an even/odd register pair and since fp0 is a scratch register, the new one is fp2). Below a patch to fix it.

diff --git a/sysdeps/powerpc/dfpu/fabsd128.c b/sysdeps/powerpc/dfpu/fabsd128.c
index b0dd73e..c1c38e8 100644
--- a/sysdeps/powerpc/dfpu/fabsd128.c
+++ b/sysdeps/powerpc/dfpu/fabsd128.c
@@ -26,7 +26,7 @@ __fabsd128 (_Decimal128 x)
 {
   /* Half part os decimal128 constainst the sign bit at same position as
      binary64, so the instruction works for both formats.  */
-  register _Decimal128 input asm("fr0") = x;
+  register _Decimal128 input asm("fr2") = x;
   _Decimal128 ret;
   asm ("fabs  %1, %0\n"
        : "=f"(ret)

**Comment by tuliom** [comment]
Adhemerval,
I confirmed your patch does solve the problem.
Could you re-send it as a formal contribution, please? i.e. a patch with a subject, a description (entirely based on your previous comment) and following the guidelines at [CONTRIBUTING](https://github.com/libdfp/libdfp/blob/master/CONTRIBUTING).

**Comment by zatrazz** [comment]
Done, I fixed other implementations as well.

https://github.com/libdfp/libdfp/pull/17
