### ISSUE TITLE
Conversions wrongly clear already-raised "inexact" exception

### ISSUE THREAD

**Issue by jsm28** [libdfp/libdfp#34]
At least some libdfp conversions between decimal and binary types wrongly clear the "inexact" exception when it was raised before the conversion; the exception flag bits are sticky and should not be cleared except by a few functions such as feclearexcept.  For example, the attached test prints

inexact wrongly cleared

instead of the expected

inexact still raised as expected

that it does with the libgcc conversions.
[testinex2.txt](https://github.com/libdfp/libdfp/files/67526/testinex2.txt)

**Comment by racardoso** [comment]
The problem is in this line https://github.com/libdfp/libdfp/blob/c5f353ed6cef0571b8056a8bee3d4db742722faf/base-math/trunctddf.c#L105 it always clear `FE_INEXACT` no matter if we force a exception or if we produce a inexact result. Comment this line make the test pass and I didn't see any side effects. I don't know why this line was added. I am working on it.
