### ISSUE TITLE
Fails to build on s390x due to unrecognized srnmt opcode

### ISSUE THREAD

**Issue by fweimer** [libdfp/libdfp#62]
I get this:

    ../sysdeps/s390/dfpu/fe_decround.c: Assembler messages:
    ../sysdeps/s390/dfpu/fe_decround.c:56: Error: Unrecognized opcode: `srnmt'
    make: *** [fe_decround.o] Error 1

This happens with binutils 2.28-8.el7 (from devtoolset-7-binutils-2.28-8.el7.s390x) and gcc 7.2.1 (from devtoolset-7-gcc-7.2.1-1.el7.s390x).

**Comment by tuliom** [comment]
@fweimer, which parameters are you using to configure libdfp?

**Comment by tuliom** [comment]
For the record: I didn't find any recent changes to Binutils that affected srnmt and I couldn't reproduce this issue with gcc version 7.1.1 20170622.

**Comment by fweimer** [comment]
@tuliom, I'm just using the default flags.

**Comment by tuliom** [comment]
I've just reproduced this bug.

**Comment by tuliom** [comment]
The default value of -march on RHEL7's gcc is z9-ec, which does have DFP instructions.

devtoolset-7 defaults to -march=z9-109, which doesn't have DFP instructions.

@fweimer If libdfp is configured using --with-cpu=z9-109, the build and tests will pass fine.  However, I strongly suggest to use at least --with-cpu=z9-ec in order to use DFP instructions.
